export interface LocationData {
  slug: string;
  city: string;
  state: string;
  phone: string;
  address: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
  coordinates?: {
    lat: number;
    lng: number;
  };
  serviceAreas: string[];
  services: string[];
}

export const LOCATIONS: LocationData[] = [
  {
    slug: 'memphis',
    city: 'Memphis',
    state: 'TN',
    phone: '(901) 367-3000',
    address: {
      street: '4690 Hungerford Road',
      city: 'Memphis',
      state: 'TN',
      zip: '38118',
    },
    coordinates: { lat: 35.1495, lng: -90.049 },
    serviceAreas: [
      'Bartlett',
      'Germantown',
      'Collierville',
      'Cordova',
      'Southaven',
      'Olive Branch',
    ],
    services: ['residential', 'commercial', 'supply-chain', 'storage'],
  },
  {
    slug: 'chicago',
    city: 'Chicago',
    state: 'IL',
    phone: '(630) 438-5060',
    address: {
      street: '1307 North Lombard Road, Suite A',
      city: 'Lombard',
      state: 'IL',
      zip: '60148',
    },
    coordinates: { lat: 41.8781, lng: -87.6298 },
    serviceAreas: ['Naperville', 'Evanston', 'Oak Park', 'Schaumburg', 'Aurora', 'Joliet'],
    services: ['residential', 'commercial', 'supply-chain', 'storage'],
  },
  {
    slug: 'atlanta',
    city: 'Atlanta',
    state: 'GA',
    phone: '(770) 368-0368',
    address: {
      street: '6950 Business Court',
      city: 'Doraville',
      state: 'GA',
      zip: '30340',
    },
    coordinates: { lat: 33.749, lng: -84.388 },
    serviceAreas: ['Alpharetta', 'Sandy Springs', 'Marietta', 'Decatur', 'Buckhead', 'Roswell'],
    services: ['residential', 'commercial', 'supply-chain', 'storage'],
  },
  {
    slug: 'dallas',
    city: 'Dallas',
    state: 'TX',
    phone: '(972) 242-0511',
    address: {
      street: '1405 Crescent Drive',
      city: 'Carrollton',
      state: 'TX',
      zip: '75006',
    },
    coordinates: { lat: 32.7767, lng: -96.797 },
    serviceAreas: ['Plano', 'Frisco', 'Irving', 'Garland', 'Arlington', 'Fort Worth'],
    services: ['residential', 'commercial', 'supply-chain', 'storage'],
  },
  {
    slug: 'houston',
    city: 'Houston',
    state: 'TX',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Houston', state: 'TX', zip: '77001' },
    coordinates: { lat: 29.7604, lng: -95.3698 },
    serviceAreas: ['Sugar Land', 'The Woodlands', 'Katy', 'Pearland', 'Pasadena'],
    services: ['residential', 'commercial', 'supply-chain'],
  },
  {
    slug: 'nashville',
    city: 'Nashville',
    state: 'TN',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Nashville', state: 'TN', zip: '37201' },
    coordinates: { lat: 36.1627, lng: -86.7816 },
    serviceAreas: ['Brentwood', 'Franklin', 'Murfreesboro', 'Hendersonville', 'Smyrna'],
    services: ['residential', 'commercial', 'storage'],
  },
  {
    slug: 'charlotte',
    city: 'Charlotte',
    state: 'NC',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Charlotte', state: 'NC', zip: '28201' },
    coordinates: { lat: 35.2271, lng: -80.8431 },
    serviceAreas: ['Huntersville', 'Concord', 'Matthews', 'Mooresville', 'Gastonia'],
    services: ['residential', 'commercial', 'supply-chain', 'storage', 'warehousing'],
  },
  {
    slug: 'raleigh',
    city: 'Raleigh',
    state: 'NC',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Raleigh', state: 'NC', zip: '27601' },
    coordinates: { lat: 35.7796, lng: -78.6382 },
    serviceAreas: ['Durham', 'Chapel Hill', 'Cary', 'Apex', 'Wake Forest'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'tampa',
    city: 'Tampa',
    state: 'FL',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Tampa', state: 'FL', zip: '33601' },
    coordinates: { lat: 27.9506, lng: -82.4572 },
    serviceAreas: ['St. Petersburg', 'Clearwater', 'Brandon', 'Lakeland', 'Sarasota'],
    services: ['residential', 'commercial', 'storage'],
  },
  {
    slug: 'kansas-city',
    city: 'Kansas City',
    state: 'MO',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Kansas City', state: 'MO', zip: '64101' },
    coordinates: { lat: 39.0997, lng: -94.5786 },
    serviceAreas: ['Overland Park', 'Lenexa', 'Olathe', 'Independence', "Lee's Summit"],
    services: ['residential', 'commercial', 'supply-chain'],
  },
  {
    slug: 'sacramento',
    city: 'Sacramento',
    state: 'CA',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Sacramento', state: 'CA', zip: '95814' },
    coordinates: { lat: 38.5816, lng: -121.4944 },
    serviceAreas: ['Roseville', 'Elk Grove', 'Folsom', 'Davis', 'Woodland'],
    services: ['residential', 'commercial', 'supply-chain', 'storage'],
  },
  {
    slug: 'los-angeles',
    city: 'Los Angeles',
    state: 'CA',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Los Angeles', state: 'CA', zip: '90001' },
    coordinates: { lat: 34.0522, lng: -118.2437 },
    serviceAreas: ['Pasadena', 'Long Beach', 'Santa Monica', 'Glendale', 'Burbank'],
    services: ['residential', 'commercial', 'supply-chain'],
  },
  {
    slug: 'san-francisco',
    city: 'San Francisco',
    state: 'CA',
    phone: '(800) 288-7396',
    address: { street: '', city: 'San Francisco', state: 'CA', zip: '94102' },
    coordinates: { lat: 37.7749, lng: -122.4194 },
    serviceAreas: ['Oakland', 'Berkeley', 'San Jose', 'Palo Alto', 'Fremont'],
    services: ['residential', 'commercial', 'supply-chain', 'storage'],
  },
  {
    slug: 'boston',
    city: 'Boston',
    state: 'MA',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Boston', state: 'MA', zip: '02101' },
    coordinates: { lat: 42.3601, lng: -71.0589 },
    serviceAreas: ['Cambridge', 'Somerville', 'Quincy', 'Brookline', 'Newton'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'new-orleans',
    city: 'New Orleans',
    state: 'LA',
    phone: '(800) 288-7396',
    address: { street: '', city: 'New Orleans', state: 'LA', zip: '70112' },
    coordinates: { lat: 29.9511, lng: -90.0715 },
    serviceAreas: ['Metairie', 'Kenner', 'Slidell', 'Gretna', 'Baton Rouge'],
    services: ['residential', 'commercial', 'supply-chain'],
  },
  {
    slug: 'baton-rouge',
    city: 'Baton Rouge',
    state: 'LA',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Baton Rouge', state: 'LA', zip: '70801' },
    coordinates: { lat: 30.4515, lng: -91.1871 },
    serviceAreas: ['Zachary', 'Prairieville', 'Denham Springs', 'Gonzales'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'louisville',
    city: 'Louisville',
    state: 'KY',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Louisville', state: 'KY', zip: '40201' },
    coordinates: { lat: 38.2527, lng: -85.7585 },
    serviceAreas: ['Lexington', 'Jeffersonville', 'New Albany', 'Clarksville'],
    services: ['residential', 'commercial', 'supply-chain'],
  },
  {
    slug: 'knoxville',
    city: 'Knoxville',
    state: 'TN',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Knoxville', state: 'TN', zip: '37901' },
    coordinates: { lat: 35.9606, lng: -83.9207 },
    serviceAreas: ['Oak Ridge', 'Maryville', 'Alcoa', 'Clinton'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'chattanooga',
    city: 'Chattanooga',
    state: 'TN',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Chattanooga', state: 'TN', zip: '37401' },
    coordinates: { lat: 35.0456, lng: -85.3097 },
    serviceAreas: ['Cleveland', 'East Ridge', 'Red Bank', 'Signal Mountain'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'huntsville',
    city: 'Huntsville',
    state: 'AL',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Huntsville', state: 'AL', zip: '35801' },
    coordinates: { lat: 34.7304, lng: -86.5861 },
    serviceAreas: ['Madison', 'Decatur', 'Athens', 'Florence'],
    services: ['residential', 'commercial', 'supply-chain'],
  },
  {
    slug: 'birmingham',
    city: 'Birmingham',
    state: 'AL',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Birmingham', state: 'AL', zip: '35203' },
    coordinates: { lat: 33.5186, lng: -86.8104 },
    serviceAreas: ['Hoover', 'Vestavia Hills', 'Homewood', 'Trussville'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'jackson',
    city: 'Jackson',
    state: 'MS',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Jackson', state: 'MS', zip: '39201' },
    coordinates: { lat: 32.2988, lng: -90.1848 },
    serviceAreas: ['Ridgeland', 'Madison', 'Brandon', 'Pearl'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'tulsa',
    city: 'Tulsa',
    state: 'OK',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Tulsa', state: 'OK', zip: '74103' },
    coordinates: { lat: 36.154, lng: -95.9928 },
    serviceAreas: ['Broken Arrow', 'Owasso', 'Bixby', 'Jenks'],
    services: ['residential', 'commercial', 'supply-chain'],
  },
  {
    slug: 'oklahoma-city',
    city: 'Oklahoma City',
    state: 'OK',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Oklahoma City', state: 'OK', zip: '73101' },
    coordinates: { lat: 35.4676, lng: -97.5164 },
    serviceAreas: ['Edmond', 'Norman', 'Moore', 'Midwest City'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'san-antonio',
    city: 'San Antonio',
    state: 'TX',
    phone: '(800) 288-7396',
    address: { street: '', city: 'San Antonio', state: 'TX', zip: '78201' },
    coordinates: { lat: 29.4241, lng: -98.4936 },
    serviceAreas: ['New Braunfels', 'Schertz', 'Converse', 'Universal City'],
    services: ['residential', 'commercial', 'supply-chain'],
  },
  {
    slug: 'milwaukee',
    city: 'Milwaukee',
    state: 'WI',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Milwaukee', state: 'WI', zip: '53201' },
    coordinates: { lat: 43.0389, lng: -87.9065 },
    serviceAreas: ['Wauwatosa', 'West Allis', 'Greenfield', 'Shorewood'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'madison',
    city: 'Madison',
    state: 'WI',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Madison', state: 'WI', zip: '53701' },
    coordinates: { lat: 43.0731, lng: -89.4012 },
    serviceAreas: ['Middleton', 'Sun Prairie', 'Fitchburg', 'Monona'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'akron',
    city: 'Akron',
    state: 'OH',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Akron', state: 'OH', zip: '44301' },
    coordinates: { lat: 41.0814, lng: -81.519 },
    serviceAreas: ['Canton', 'Stow', 'Cuyahoga Falls', 'Fairlawn'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'new-jersey',
    city: 'New Jersey',
    state: 'NJ',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Newark', state: 'NJ', zip: '07101' },
    coordinates: { lat: 40.7128, lng: -74.0059 },
    serviceAreas: ['Newark', 'Jersey City', 'Hoboken', 'Edison', 'Trenton'],
    services: ['residential', 'commercial', 'supply-chain'],
  },
  {
    slug: 'fort-lauderdale',
    city: 'Fort Lauderdale',
    state: 'FL',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Fort Lauderdale', state: 'FL', zip: '33301' },
    coordinates: { lat: 26.1224, lng: -80.1373 },
    serviceAreas: ['Boca Raton', 'Pompano Beach', 'Hollywood', 'Coral Springs'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'charleston',
    city: 'Charleston',
    state: 'SC',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Charleston', state: 'SC', zip: '29401' },
    coordinates: { lat: 32.7765, lng: -79.9311 },
    serviceAreas: ['Mount Pleasant', 'North Charleston', 'Summerville', 'Goose Creek'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'delaware',
    city: 'Delaware',
    state: 'DE',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Wilmington', state: 'DE', zip: '19801' },
    coordinates: { lat: 39.7447, lng: -75.5484 },
    serviceAreas: ['Dover', 'Newark', 'Middletown', 'Smyrna'],
    services: ['residential', 'commercial'],
  },
  {
    slug: 'lancaster',
    city: 'Lancaster',
    state: 'PA',
    phone: '(800) 288-7396',
    address: { street: '', city: 'Lancaster', state: 'PA', zip: '17601' },
    coordinates: { lat: 40.0379, lng: -76.3055 },
    serviceAreas: ['York', 'Harrisburg', 'Reading', 'Lebanon', 'Mechanicsburg'],
    services: ['residential', 'commercial', 'supply-chain'],
  },
];

export function getLocationBySlug(slug: string): LocationData | undefined {
  return LOCATIONS.find((loc) => loc.slug === slug);
}

export function getAllLocationSlugs(): string[] {
  return LOCATIONS.map((loc) => loc.slug);
}
